---
config:
  theme: default
  htmlLabels: false
  markdownAutoWrap: false
  wrap: false
---
graph TD
    A[dc=ldap,dc=lantolin42,<br>dc=internal] 
    A --- C[ou=gru-labs]
    C --- K[uid=kevin]
    C --- BOB[uid=bob]
    C --- ST[uid=stuart]
